spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AQBmCfTwyYRIkn/Jy72Oe8q3pMmxj+bSDZHYK9HYEqMYbIq74lYiajJoyx+t4B7TOLcyRnBEGKSZ8LRLJcpTajoyEplVqzzjP7zedCDHGb9ZwVFEaMvn1IBqrA2mjTnlJTG/P/ZYNDz35bcfFigOJRSYNKsI66zgHjbGr83NU/pZL/asW1hdiw60rHzZBOGYHHAcOvOPHd+AyPIfy58PAhgQzM8ZLyyz3Rh40wySNS5Jb8vxd++GQcIbVrTxdAOl8nEo86+zbthGrf1XxdItFjqa8Rp45pyotM8UzSssVWU0IsP8oSfqlMNPrDylRJGsMg6e48KLlS9AA6h3uJ1iO9K/+YmQVDiyrAZdFwvPZt8GZtdOvmEeAWSPEVET7w2PDcQ='

token:
  expiration_time: 86400000
  secret: my_token_default

gateway:
  ip: 180.70.31.115
