spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AQA2LSHXau39CoB9R3pyZ0cbnP8vxVCvLkDEen/D84pr00ZIMoiruclGoF5hTOF0pGBiIzRtUODkHBaUhgdCcp/7H8lIfKiYUnN9uoXlwhIROOGWjbVpsEPhBrok3Iw11FRTjgOoA/UK0eCZp8wP/llRtTS7oG+1NGMIjB+VnrHuqB1Xx5JqxsurDtORza7e8SIHRy3C9YAs3BH7pjXTgUKTWg5b+107KfjP5f3V4y8Oa/g0ouFjsqKMYdLbaVviv8zY8HmA5FRDN/gfb282v9L36xV1uTWmK1sR2WBekvGfpoa1OhlhOGbHr7tfq0+NLHHdfcViRkmvb52oo1PiuMhxXmDBXfsM/Er/6+VuCJdvojWNAxbZsfV4Kd0A3+Ph69d8bCLJiC7txLtgJOcUDYot'

token:
  expiration_time: 86400000
  secret: user-token-native-application

gateway:
  ip: 180.70.31.115
